repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
#  - repo: https://github.com/psf/black
#    rev: 22.10.0
#    hooks:
#      - id: black
#  - repo: https://github.com/itschrisrichards/code-scan-action
#    rev: 06c70aa1f26a8621b439ad6d8ebfa65bd62bc9d6
#    hooks:
#      - id: code-scan-action
#        args:
#          [
#            "--url",
#            "https://1ef7-74-96-33-87.ngrok-free.app/api/code/scan",
#            "--ignore-entities",
#            "EMAIL,URL"
#          ]
#        verbose: true
