repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
#  - repo: https://github.com/itschrisrichards/code-scan-action
#    rev: 9c6aefabdd01b653abca0f352e09a4fe486e5505
#    hooks:
#      - id: code-scan-action
#        verbose: true
