- id: code-scan-action
  name: Check Staged Commits for PII
  description: This hook checks if stage commit files have PII.
  entry: code_scan_action
  verbose: true
  require_serial: true
  language: python
  types: [file, text]
